error: add `ConnError` type for network connection errors
This commit adds the `ConnError` type. A `ConnError`
is returned by a `Client` or `Enclave` to indicate
that an operation failed due to a network issue.
For example, a DNS error.

Users may check whether an operation return an
error of type `ConnError` and act appropriately.

Signed-off-by: Andreas Auernhammer <hi@aead.dev>